//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mnxi_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_category
    {
        public int cate_id { get; set; }
        public int cate_type_id { get; set; }
        public string cate_name { get; set; }
        public string cate_code { get; set; }
        public string is_appl_yearenddona { get; set; }
        public string notes { get; set; }
        public string status { get; set; }
        public string onlyforadmin { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public string cate_des { get; set; }
        public string is_location { get; set; }
        public string RequestID { get; set; }
        public string RequestStatus { get; set; }
        public bool Mode { get; set; }
        public string QBListID { get; set; }
        public string QBEditSequence { get; set; }
    
        public virtual m_category_type m_category_type { get; set; }
    }
}
