//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mnxi_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_category_type
    {
        public m_category_type()
        {
            this.m_category = new HashSet<m_category>();
        }
    
        public int cate_type_id { get; set; }
        public string cate_type_name { get; set; }
        public string cate_type_code { get; set; }
        public string status { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public Nullable<int> menu_id { get; set; }
        public string catetype_desc { get; set; }
        public string catetype_note { get; set; }
        public string RequestID { get; set; }
        public string RequestStatus { get; set; }
        public bool Mode { get; set; }
        public string QBListID { get; set; }
        public string QBEditSequence { get; set; }
    
        public virtual ICollection<m_category> m_category { get; set; }
    }
}
