//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mnxi_db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MTSTXEntities : DbContext
    {
        public MTSTXEntities()
            : base("name=MTSTXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vw_donationsummary> vw_donationsummary { get; set; }
        public virtual DbSet<vw_PoojaBooking> vw_PoojaBooking { get; set; }
        public virtual DbSet<vw_TransactionByNameType> vw_TransactionByNameType { get; set; }
        public virtual DbSet<m_category> m_category { get; set; }
        public virtual DbSet<m_category_type> m_category_type { get; set; }
    }
}
