//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mnxi_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_donationsummary
    {
        public Nullable<long> No { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public Nullable<int> CategoryServiceId { get; set; }
        public Nullable<System.DateTime> tran_date { get; set; }
        public string CategoryTypeName { get; set; }
        public string CategoryName { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> Serv_Id { get; set; }
        public string serv_code { get; set; }
        public string status { get; set; }
        public string TransactionDate { get; set; }
        public string TransactionTime { get; set; }
        public string DevoteeName { get; set; }
        public string CollectedBy { get; set; }
        public string OnBehalfOf { get; set; }
        public string Tran_mode { get; set; }
        public string ApprovalNumber { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public decimal ReturnedAmount { get; set; }
        public decimal RepaymentAmount { get; set; }
        public decimal RefundedAmount { get; set; }
        public string ReceiptNumber { get; set; }
        public string Notes { get; set; }
        public Nullable<int> RunningId_sc_tran_id_Trans { get; set; }
        public string PayType { get; set; }
        public Nullable<int> SCid { get; set; }
        public string Is_kiosk { get; set; }
        public Nullable<decimal> GrdTotal { get; set; }
        public bool Mode { get; set; }
        public decimal DeleteAmt { get; set; }
        public decimal Bankcharges { get; set; }
        public string donationstatus { get; set; }
        public string OldReceiptNumber { get; set; }
        public string Receiptnumberfilter { get; set; }
    }
}
