//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mnxi_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PoojaBooking
    {
        public System.DateTime business_date { get; set; }
        public string remarks { get; set; }
        public string IsDeleted { get; set; }
        public int Sche_Id { get; set; }
        public string DevoteeName { get; set; }
        public string PerformedDate { get; set; }
        public string ScheduledDate { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string AssignedPriest { get; set; }
        public string ServiceName { get; set; }
        public string Address { get; set; }
        public string EmailId { get; set; }
        public string Phone { get; set; }
        public string Natshatra { get; set; }
        public string gothra { get; set; }
        public string CollectedBy { get; set; }
        public string Mode { get; set; }
        public string Approval { get; set; }
        public string type { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> Receipt { get; set; }
        public string notes { get; set; }
        public Nullable<int> SCId { get; set; }
        public string Status { get; set; }
        public string time { get; set; }
        public System.DateTime sche_date { get; set; }
        public Nullable<System.TimeSpan> start_time { get; set; }
        public Nullable<System.TimeSpan> end_time { get; set; }
    }
}
