//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mnxi_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TransactionByNameType
    {
        public string name { get; set; }
        public string TransactionDate { get; set; }
        public string realchecknumber { get; set; }
        public string TransactionType { get; set; }
        public Nullable<int> TotalItems { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
