//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_appn_code
    {
        public d_appn_code()
        {
            this.d_user_roles = new HashSet<d_user_roles>();
        }
    
        public int appn_code_id { get; set; }
        public int appn_code_type_id { get; set; }
        public string appn_code_name { get; set; }
        public string appn_code_title { get; set; }
        public string appn_code_desc { get; set; }
        public Nullable<int> sort_order { get; set; }
        public string status { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public Nullable<int> ref_id { get; set; }
    
        public virtual ICollection<d_user_roles> d_user_roles { get; set; }
        public virtual m_appn_code_type m_appn_code_type { get; set; }
    }
}
