//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_comp
    {
        public d_comp()
        {
            this.d_user_comp = new HashSet<d_user_comp>();
        }
    
        public int comp_id { get; set; }
        public string comp_name { get; set; }
        public string comp_addr { get; set; }
        public string comp_city { get; set; }
        public Nullable<short> comp_state { get; set; }
        public string comp_state_others { get; set; }
        public Nullable<short> comp_cntry { get; set; }
        public string comp_cntry_others { get; set; }
        public string comp_phone { get; set; }
        public string comp_zip { get; set; }
        public string comp_web_url { get; set; }
        public string status { get; set; }
        public int comp_crea_owner { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public string RequestID { get; set; }
        public string RequestStatus { get; set; }
        public bool Mode { get; set; }
        public string QBListID { get; set; }
        public string QBEditSequence { get; set; }
        public Nullable<int> createdby { get; set; }
    
        public virtual QBHoma_Status QBHoma_Status { get; set; }
        public virtual ICollection<d_user_comp> d_user_comp { get; set; }
    }
}
