//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_memorize_filter_data
    {
        public int DataFilterId { get; set; }
        public int MemorizeId { get; set; }
        public string Columns { get; set; }
        public string FilterValues { get; set; }
    
        public virtual d_memorize_filter d_memorize_filter { get; set; }
    }
}
