//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_memorize_filter_fonts
    {
        public int FontValueId { get; set; }
        public int MemorizeId { get; set; }
        public int FontId { get; set; }
        public string FontFamily { get; set; }
        public string FontSize { get; set; }
        public string FontStyle { get; set; }
        public string TextDecoration { get; set; }
        public string Color { get; set; }
    
        public virtual d_memorize_filter d_memorize_filter { get; set; }
        public virtual m_memorize_font m_memorize_font { get; set; }
    }
}
