//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_memorize_filter
    {
        public d_memorize_filter()
        {
            this.d_memorize_filter_data = new HashSet<d_memorize_filter_data>();
            this.d_memorize_filter_fonts = new HashSet<d_memorize_filter_fonts>();
        }
    
        public int MemorizeId { get; set; }
        public int ReportId { get; set; }
        public decimal Dates { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string ColumnsFilter { get; set; }
        public bool IsCompanyNameSelected { get; set; }
        public bool IsReportTitleSelected { get; set; }
        public bool IsSubTitleSelected { get; set; }
        public bool IsDatePreparedSelected { get; set; }
        public bool IsTimePreparedSelected { get; set; }
        public bool IsShowHeader { get; set; }
        public bool IsPageNoSelected { get; set; }
        public bool IsExtraFooterSelected { get; set; }
        public bool IsShowFooter { get; set; }
        public string CompanyName { get; set; }
        public string ReportTitle { get; set; }
        public string SubTitle { get; set; }
        public string DatePrepared { get; set; }
        public string PageNo { get; set; }
        public string ExtraFooterLine { get; set; }
        public string PageAlignment { get; set; }
        public string ShowNegativeNos { get; set; }
        public bool IsShowNegativeNosinRed { get; set; }
        public bool IsDivideby1000 { get; set; }
        public bool IsExcept0Amts { get; set; }
        public bool IsWithoutCents { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string GroupBy { get; set; }
        public string TotalBy { get; set; }
    
        public virtual ICollection<d_memorize_filter_data> d_memorize_filter_data { get; set; }
        public virtual ICollection<d_memorize_filter_fonts> d_memorize_filter_fonts { get; set; }
        public virtual m_memorize_report m_memorize_report { get; set; }
    }
}
