//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_priest_info
    {
        public int priest_info_id { get; set; }
        public int priest_id { get; set; }
        public string lang { get; set; }
        public string priest_type { get; set; }
        public string Notes { get; set; }
        public Nullable<int> color { get; set; }
    }
}
