//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_relatives
    {
        public int rel_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> rel_type_id { get; set; }
        public string rel_fname { get; set; }
        public string rel_mname { get; set; }
        public string rel_lname { get; set; }
        public Nullable<System.DateTime> rel_dob { get; set; }
        public Nullable<int> rel_nat { get; set; }
        public Nullable<System.DateTime> rel_wdate { get; set; }
        public string rel_gothra { get; set; }
        public string rel_email { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
    
        public virtual m_user m_user { get; set; }
    }
}
