//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_user_comp
    {
        public int user_comp_id { get; set; }
        public int comp_id { get; set; }
        public int user_id { get; set; }
        public string status { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public string RequestID { get; set; }
        public string RequestStatus { get; set; }
        public bool Mode { get; set; }
        public string QBListID { get; set; }
        public string QBEditSequence { get; set; }
    
        public virtual d_comp d_comp { get; set; }
        public virtual QBHoma_Status QBHoma_Status { get; set; }
    }
}
