//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_appn_menu_mgmt
    {
        public m_appn_menu_mgmt()
        {
            this.m_home_panel = new HashSet<m_home_panel>();
        }
    
        public int menu_id { get; set; }
        public string menu_name { get; set; }
        public string menu_page_name { get; set; }
        public string menu_title { get; set; }
        public string is_report { get; set; }
        public string is_role_based { get; set; }
        public Nullable<int> cate_type_id { get; set; }
        public string is_dynamic { get; set; }
        public Nullable<int> menu_order { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string status { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public Nullable<int> is_menu { get; set; }
        public Nullable<int> homedisplay { get; set; }
        public string homa_menu { get; set; }
    
        public virtual ICollection<m_home_panel> m_home_panel { get; set; }
    }
}
