//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_appl_mailconfig_mgmt
    {
        public int mail_config_id { get; set; }
        public string mail_config_name { get; set; }
        public int mailserver_id { get; set; }
    }
}
