//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_appn_mailserver_mgmt
    {
        public int mailserver_id { get; set; }
        public string mailserver_name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string displayname { get; set; }
        public string status { get; set; }
        public string portno { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public string mailserver_mailid { get; set; }
    }
}
