//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_appn_mailconfig_mgmt
    {
        public int bulkmail { get; set; }
        public int transactionmail { get; set; }
        public int receiptmail { get; set; }
        public int welcomemail { get; set; }
        public int newslettermail { get; set; }
        public int eventmail { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public Nullable<int> userprofile { get; set; }
    }
}
