//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_authorise_net_tran_history
    {
        public int tran_log_id { get; set; }
        public string session_id { get; set; }
        public Nullable<int> sc_cart_id { get; set; }
        public string paid_user { get; set; }
        public string name_on_the_card { get; set; }
        public Nullable<System.DateTime> tran_submitted_date { get; set; }
        public string tran_submited_time { get; set; }
        public Nullable<System.DateTime> tran_response_date { get; set; }
        public string tran_response_time { get; set; }
        public Nullable<int> tran_submitted_by { get; set; }
        public Nullable<System.DateTime> tran_created_on { get; set; }
        public Nullable<System.DateTime> tran_modified_on { get; set; }
        public string tran_pay_status { get; set; }
        public string tran_response_status { get; set; }
        public string tran_order_id { get; set; }
        public string tran_response_message { get; set; }
        public string tran_exception_message { get; set; }
        public Nullable<decimal> tran_amount { get; set; }
        public string user_type { get; set; }
        public string tran_payment_mode { get; set; }
        public string Is_Kiosk { get; set; }
    }
}
