//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_dona_serv_fee
    {
        public Nullable<int> tran_id { get; set; }
        public Nullable<int> serv_type_id { get; set; }
        public Nullable<int> serv_id { get; set; }
        public Nullable<int> pooj_id { get; set; }
        public string cate_id { get; set; }
        public Nullable<int> user_Id_comp_id { get; set; }
        public Nullable<System.DateTime> tran_date { get; set; }
        public string tran_time { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string mode_of_tran_id { get; set; }
        public string tran_numb_from_vend { get; set; }
        public string name_on_the_check { get; set; }
        public string addr_on_the_check { get; set; }
        public Nullable<System.DateTime> date_on_the_check { get; set; }
        public string chec_numb { get; set; }
        public string bank_name { get; set; }
        public string notes { get; set; }
        public Nullable<int> coll_by { get; set; }
        public Nullable<int> prie_id { get; set; }
        public Nullable<int> deleted_user_id { get; set; }
        public Nullable<System.DateTime> deleted_date { get; set; }
        public string is_deleted { get; set; }
        public string namedcheck { get; set; }
        public string chec_stat { get; set; }
        public string chec_reco { get; set; }
        public string item_id { get; set; }
        public string service_type { get; set; }
        public Nullable<int> event_id_reff { get; set; }
        public string is_returned { get; set; }
        public string ret_teason { get; set; }
        public string is_refunded { get; set; }
        public Nullable<System.DateTime> ret_date { get; set; }
        public Nullable<System.DateTime> ref_date { get; set; }
        public string ref_reason { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public string comp_id { get; set; }
        public Nullable<decimal> ref_amount { get; set; }
        public string ret_mode { get; set; }
        public string ref_mode { get; set; }
        public Nullable<decimal> ret_amount { get; set; }
        public string ret_chk_number { get; set; }
        public string ref_chk_number { get; set; }
        public string ref_bank_name { get; set; }
        public string ret_bank_name { get; set; }
        public Nullable<System.DateTime> ret_check_date { get; set; }
        public Nullable<System.DateTime> ref_check_date { get; set; }
        public Nullable<int> ret_c_by { get; set; }
        public Nullable<int> ref_c_by { get; set; }
        public string ret_chk_name { get; set; }
        public string ref_chk_name { get; set; }
        public Nullable<int> sche_id { get; set; }
        public string pay_type { get; set; }
        public Nullable<int> walkindevoid { get; set; }
        public string RequestID { get; set; }
        public string RequestStatus { get; set; }
        public bool Mode { get; set; }
    
        public virtual QBHoma_Status QBHoma_Status { get; set; }
    }
}
