//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_event
    {
        public int even_id { get; set; }
        public string even_name { get; set; }
        public string even_desc { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string start_time { get; set; }
        public string end_time { get; set; }
        public string place { get; set; }
        public string displayinhome { get; set; }
        public string even_coord { get; set; }
        public string even_spon { get; set; }
        public decimal even_spon_amt { get; set; }
        public string even_attach { get; set; }
        public string notes { get; set; }
        public string recu_patt { get; set; }
        public string recu_info { get; set; }
        public string even_mailer_image { get; set; }
        public string status { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public Nullable<short> alldayevent { get; set; }
        public string even_color { get; set; }
        public Nullable<int> service { get; set; }
        public string online_regi { get; set; }
        public Nullable<System.DateTime> online_reg_date { get; set; }
        public Nullable<int> max_Parti { get; set; }
        public Nullable<int> Grp_size { get; set; }
        public Nullable<int> min_age { get; set; }
        public Nullable<int> max_age { get; set; }
        public string online_estatus { get; set; }
        public string KIOSK_display { get; set; }
        public string RequiresCashTickets { get; set; }
        public string KIOSK_list_pooj_item_file { get; set; }
        public string RequiresTemplePooja { get; set; }
    }
}
