//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_home_panel
    {
        public int home_pane_id { get; set; }
        public string list_name { get; set; }
        public string panel_name { get; set; }
        public string file_name { get; set; }
        public Nullable<int> panel_order { get; set; }
        public string image_name { get; set; }
        public Nullable<int> menu_id { get; set; }
        public string status { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public string Name { get; set; }
    
        public virtual m_appn_menu_mgmt m_appn_menu_mgmt { get; set; }
    }
}
