//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_memorize_report
    {
        public m_memorize_report()
        {
            this.d_memorize_filter = new HashSet<d_memorize_filter>();
        }
    
        public int ReportId { get; set; }
        public string ReportName { get; set; }
        public int ReportGroupId { get; set; }
        public string PageName { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> profileuserid { get; set; }
    
        public virtual ICollection<d_memorize_filter> d_memorize_filter { get; set; }
        public virtual m_memorize_reportgroup m_memorize_reportgroup { get; set; }
    }
}
