//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_memorize_reportgroup
    {
        public m_memorize_reportgroup()
        {
            this.m_memorize_report = new HashSet<m_memorize_report>();
        }
    
        public int ReportGroupId { get; set; }
        public string ReportGroupName { get; set; }
        public int user_id { get; set; }
    
        public virtual ICollection<m_memorize_report> m_memorize_report { get; set; }
        public virtual m_user m_user { get; set; }
    }
}
