//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_memorize_font
    {
        public m_memorize_font()
        {
            this.d_memorize_filter_fonts = new HashSet<d_memorize_filter_fonts>();
        }
    
        public int FontId { get; set; }
        public string FontName { get; set; }
    
        public virtual ICollection<d_memorize_filter_fonts> d_memorize_filter_fonts { get; set; }
    }
}
