//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_Online_Event_Regi
    {
        public string RegId { get; set; }
        public string Even_Id { get; set; }
        public string User_Id { get; set; }
        public string User_type_id { get; set; }
        public string user_type { get; set; }
        public string Orderid { get; set; }
        public string Bir_Year { get; set; }
        public string Isreg { get; set; }
    }
}
