//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_reso_sche
    {
        public int sche_id { get; set; }
        public int Cate_Serv_id { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
        public string start_time { get; set; }
        public string end_time { get; set; }
        public string recu_patt { get; set; }
        public string recu_info { get; set; }
        public int loc_id { get; set; }
        public int user_id { get; set; }
        public string user_address { get; set; }
        public decimal serv_fee { get; set; }
        public decimal loc_fee { get; set; }
        public decimal dak_fee { get; set; }
        public decimal tot_fee { get; set; }
        public int tran_id { get; set; }
        public string status { get; set; }
        public string pay_status { get; set; }
        public string notes { get; set; }
        public string isdeleted { get; set; }
        public Nullable<int> deletedby { get; set; }
        public Nullable<System.DateTime> deletedon { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public Nullable<int> recu_cnt { get; set; }
        public Nullable<decimal> extra_fee { get; set; }
        public Nullable<int> walkindevoid { get; set; }
        public Nullable<int> scid { get; set; }
        public string serv_location { get; set; }
        public string buffer { get; set; }
        public Nullable<System.DateTime> buff_sdate { get; set; }
        public Nullable<System.DateTime> buff_edate { get; set; }
        public string buff_stime { get; set; }
        public string buff_etime { get; set; }
        public string Disp_Home { get; set; }
        public string isp_Calendar { get; set; }
        public string disp_Calendar { get; set; }
    }
}
