//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_service
    {
        public int cate_serv_id { get; set; }
        public int cate_type_id { get; set; }
        public int cate_id { get; set; }
        public int serv_id { get; set; }
        public string serv_name { get; set; }
        public string serv_desc { get; set; }
        public string serv_code { get; set; }
        public string atta_file { get; set; }
        public Nullable<decimal> fee { get; set; }
        public string notes { get; set; }
        public string serv_type { get; set; }
        public string serv_location { get; set; }
        public string status { get; set; }
        public string is_pledge { get; set; }
        public string isperfectpooja { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string recu_patt { get; set; }
        public string recu_info { get; set; }
        public string home_page { get; set; }
        public string KIOSK_display { get; set; }
        public string KIOSK_list_pooj_item_file { get; set; }
        public string KIOSK_pooj_desc { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public string Access_view { get; set; }
        public string serv_note { get; set; }
        public string duration { get; set; }
        public string IsMulti_fee { get; set; }
        public string RequiresCashTickets { get; set; }
        public string RequiresPriestScheduling { get; set; }
        public string isQuicklink { get; set; }
        public string RequestID { get; set; }
        public string RequestStatus { get; set; }
        public bool Mode { get; set; }
        public string QBListID { get; set; }
        public string QBEditSequence { get; set; }
        public string RequiresTemplePooja { get; set; }
        public string DispCalendar { get; set; }
    
        public virtual m_category_type m_category_type { get; set; }
        public virtual QBHoma_Status QBHoma_Status { get; set; }
    }
}
