//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_shop_cart
    {
        public int sc_cart_id { get; set; }
        public int user_id { get; set; }
        public string sess_id { get; set; }
        public Nullable<System.DateTime> cart_date { get; set; }
        public Nullable<decimal> gros_amou { get; set; }
        public Nullable<decimal> disc_perc { get; set; }
        public Nullable<decimal> disc_amou { get; set; }
        public Nullable<decimal> sale_tax { get; set; }
        public Nullable<decimal> net_amou { get; set; }
        public string notes { get; set; }
        public string walk_in_devo_f_name { get; set; }
        public string walk_in_devo_l_name { get; set; }
        public string Walk_In_Devo_Addr { get; set; }
        public Nullable<int> Walk_In_Devo_nat { get; set; }
        public string Walk_In_Devo_Goth { get; set; }
        public string Walk_In_Devo_City { get; set; }
        public Nullable<int> Walk_In_Devo_State { get; set; }
        public string Walk_In_Devo_State_others { get; set; }
        public Nullable<int> Walk_In_Devo_Cntry { get; set; }
        public string Walk_In_Devo_Cntry_Others { get; set; }
        public string Walk_In_Devo_Zip { get; set; }
        public string Walk_In_Devo_Email { get; set; }
        public string CC_Fail_Msg { get; set; }
        public string CC_Resp_Code { get; set; }
        public Nullable<decimal> Rep_Amou { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public Nullable<int> receipt_id { get; set; }
        public string pay_type { get; set; }
        public Nullable<int> walkindevoid { get; set; }
        public string RequestID { get; set; }
        public string RequestStatus { get; set; }
        public bool Mode { get; set; }
        public string old_receiptno { get; set; }
    
        public virtual QBHoma_Status QBHoma_Status { get; set; }
    }
}
