//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_shop_cart_tran
    {
        public Nullable<int> sc_tran_id { get; set; }
        public Nullable<int> sc_cart_id { get; set; }
        public Nullable<int> inve_cate_type_id { get; set; }
        public Nullable<int> inve_cate_id { get; set; }
        public Nullable<int> inve_serv_Id { get; set; }
        public Nullable<int> numb_unit { get; set; }
        public Nullable<decimal> total { get; set; }
        public string spl_payment { get; set; }
        public string performtime { get; set; }
        public Nullable<System.DateTime> performdate { get; set; }
        public Nullable<decimal> ref_amt { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public string even_type { get; set; }
        public string even_ref { get; set; }
        public Nullable<int> sche_id { get; set; }
        public string RequestID { get; set; }
        public string RequestStatus { get; set; }
        public bool Mode { get; set; }
        public string Is_Kiosk { get; set; }
    
        public virtual QBHoma_Status QBHoma_Status { get; set; }
    }
}
