//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_Temple_IncomeAccounts
    {
        public int No { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public bool Checked { get; set; }
        public int Sublevel { get; set; }
        public string ParentRef { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    }
}
