//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_time_zone
    {
        public m_time_zone()
        {
            this.m_temple = new HashSet<m_temple>();
        }
    
        public int timezoneid { get; set; }
        public string timezone { get; set; }
        public Nullable<int> hours { get; set; }
        public Nullable<int> minutes { get; set; }
        public Nullable<int> daylightfrom { get; set; }
        public Nullable<int> daylightto { get; set; }
        public Nullable<int> daylighthours { get; set; }
        public Nullable<int> daylightminutes { get; set; }
    
        public virtual ICollection<m_temple> m_temple { get; set; }
    }
}
