//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_user
    {
        public m_user()
        {
            this.d_relatives = new HashSet<d_relatives>();
            this.m_logi = new HashSet<m_logi>();
            this.m_memorize_reportgroup = new HashSet<m_memorize_reportgroup>();
        }
    
        public int user_id { get; set; }
        public string bar_code_id { get; set; }
        public string devotee_code { get; set; }
        public Nullable<int> prefix { get; set; }
        public string f_name { get; set; }
        public string m_name { get; set; }
        public string l_name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public Nullable<int> state { get; set; }
        public string state_others { get; set; }
        public string zip_code { get; set; }
        public Nullable<int> country { get; set; }
        public string cntry_others { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<int> natshatra { get; set; }
        public string gotra { get; set; }
        public string mobile { get; set; }
        public string work_phone { get; set; }
        public string work_phone_extn { get; set; }
        public string home_phone { get; set; }
        public string pers_email { get; set; }
        public string work_email { get; set; }
        public string pref_email { get; set; }
        public string pref_call { get; set; }
        public Nullable<int> user_role { get; set; }
        public Nullable<int> memb_serv_id { get; set; }
        public Nullable<int> comm_spon_serv_id { get; set; }
        public string heri_clas_stud { get; set; }
        public string status { get; set; }
        public string recv_email { get; set; }
        public string gender { get; set; }
        public string recv_magazine { get; set; }
        public string recv_tx_letter { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public string email_verified { get; set; }
        public string Emailverificationcode { get; set; }
        public string RequestID { get; set; }
        public string RequestStatus { get; set; }
        public bool Mode { get; set; }
        public string QBListID { get; set; }
        public string QBEditSequence { get; set; }
        public string alias_name { get; set; }
        public string alias_L_name { get; set; }
    
        public virtual ICollection<d_relatives> d_relatives { get; set; }
        public virtual ICollection<m_logi> m_logi { get; set; }
        public virtual ICollection<m_memorize_reportgroup> m_memorize_reportgroup { get; set; }
        public virtual d_user_roles d_user_roles { get; set; }
        public virtual QBHoma_Status QBHoma_Status { get; set; }
    }
}
