//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MTSTXEntities : DbContext
    {
        public MTSTXEntities()
            : base("name=MTSTXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<d_appn_code> d_appn_code { get; set; }
        public virtual DbSet<d_comp> d_comp { get; set; }
        public virtual DbSet<d_memorize_filter> d_memorize_filter { get; set; }
        public virtual DbSet<d_memorize_filter_data> d_memorize_filter_data { get; set; }
        public virtual DbSet<d_memorize_filter_fonts> d_memorize_filter_fonts { get; set; }
        public virtual DbSet<d_prie_leave_details> d_prie_leave_details { get; set; }
        public virtual DbSet<d_prie_leave_recu> d_prie_leave_recu { get; set; }
        public virtual DbSet<d_priest_info> d_priest_info { get; set; }
        public virtual DbSet<d_publ_newsletter> d_publ_newsletter { get; set; }
        public virtual DbSet<d_relatives> d_relatives { get; set; }
        public virtual DbSet<d_user_comp> d_user_comp { get; set; }
        public virtual DbSet<m_appl_form> m_appl_form { get; set; }
        public virtual DbSet<m_appn_code_type> m_appn_code_type { get; set; }
        public virtual DbSet<m_appn_mailserver_mgmt> m_appn_mailserver_mgmt { get; set; }
        public virtual DbSet<m_appn_menu_mgmt> m_appn_menu_mgmt { get; set; }
        public virtual DbSet<m_category> m_category { get; set; }
        public virtual DbSet<m_category_type> m_category_type { get; set; }
        public virtual DbSet<m_even_recu> m_even_recu { get; set; }
        public virtual DbSet<m_event> m_event { get; set; }
        public virtual DbSet<m_home_gallery> m_home_gallery { get; set; }
        public virtual DbSet<m_home_panel> m_home_panel { get; set; }
        public virtual DbSet<m_join_mail_list> m_join_mail_list { get; set; }
        public virtual DbSet<m_logi> m_logi { get; set; }
        public virtual DbSet<m_mailgroup> m_mailgroup { get; set; }
        public virtual DbSet<m_memorize_font> m_memorize_font { get; set; }
        public virtual DbSet<m_memorize_report> m_memorize_report { get; set; }
        public virtual DbSet<m_memorize_reportgroup> m_memorize_reportgroup { get; set; }
        public virtual DbSet<m_newsletter_template> m_newsletter_template { get; set; }
        public virtual DbSet<m_publ> m_publ { get; set; }
        public virtual DbSet<m_service> m_service { get; set; }
        public virtual DbSet<m_shop_cart> m_shop_cart { get; set; }
        public virtual DbSet<m_temple> m_temple { get; set; }
        public virtual DbSet<m_Temple_BankAccounts> m_Temple_BankAccounts { get; set; }
        public virtual DbSet<m_Temple_IncomeAccounts> m_Temple_IncomeAccounts { get; set; }
        public virtual DbSet<m_Temple_QBAccountSetup> m_Temple_QBAccountSetup { get; set; }
        public virtual DbSet<m_Temple_QBFilePath> m_Temple_QBFilePath { get; set; }
        public virtual DbSet<m_time_zone> m_time_zone { get; set; }
        public virtual DbSet<m_user> m_user { get; set; }
        public virtual DbSet<QBHoma_ChartOfAccount> QBHoma_ChartOfAccount { get; set; }
        public virtual DbSet<QBHoma_ChartOfAccountMapping> QBHoma_ChartOfAccountMapping { get; set; }
        public virtual DbSet<QBHoma_Customer> QBHoma_Customer { get; set; }
        public virtual DbSet<QBHoma_Expense> QBHoma_Expense { get; set; }
        public virtual DbSet<QBHoma_Income> QBHoma_Income { get; set; }
        public virtual DbSet<QBHoma_RequestType> QBHoma_RequestType { get; set; }
        public virtual DbSet<QBHoma_Status> QBHoma_Status { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<d_appn_code1> d_appn_code1 { get; set; }
        public virtual DbSet<d_def_role_priv> d_def_role_priv { get; set; }
        public virtual DbSet<d_loca_recu> d_loca_recu { get; set; }
        public virtual DbSet<d_prie_excl_service> d_prie_excl_service { get; set; }
        public virtual DbSet<d_reso_recu> d_reso_recu { get; set; }
        public virtual DbSet<d_user_roles> d_user_roles { get; set; }
        public virtual DbSet<m_appl_mailconfig_mgmt> m_appl_mailconfig_mgmt { get; set; }
        public virtual DbSet<m_appn_mailconfig_mgmt> m_appn_mailconfig_mgmt { get; set; }
        public virtual DbSet<m_authorise_net_tran_history> m_authorise_net_tran_history { get; set; }
        public virtual DbSet<m_dona_return_refund> m_dona_return_refund { get; set; }
        public virtual DbSet<m_dona_return_refund_History> m_dona_return_refund_History { get; set; }
        public virtual DbSet<m_dona_serv_fee> m_dona_serv_fee { get; set; }
        public virtual DbSet<m_gallery> m_gallery { get; set; }
        public virtual DbSet<m_Online_Event_Regi> m_Online_Event_Regi { get; set; }
        public virtual DbSet<m_reso_sche> m_reso_sche { get; set; }
        public virtual DbSet<m_shop_cart_tran> m_shop_cart_tran { get; set; }
        public virtual DbSet<QBHoma_CustomerMapping> QBHoma_CustomerMapping { get; set; }
        public virtual DbSet<QBHoma_ProcessMode> QBHoma_ProcessMode { get; set; }
        public virtual DbSet<tmplogi> tmplogis { get; set; }
        public virtual DbSet<walk_in_devo_info> walk_in_devo_info { get; set; }
        public virtual DbSet<vw_donationsummary> vw_donationsummary { get; set; }
        public virtual DbSet<vw_PoojaBooking> vw_PoojaBooking { get; set; }
        public virtual DbSet<vw_TransactionByNameType> vw_TransactionByNameType { get; set; }
    
        [DbFunction("MTSTXEntities", "fn_MonthlyDayRecurrence")]
        public virtual IQueryable<fn_MonthlyDayRecurrence_Result> fn_MonthlyDayRecurrence(Nullable<System.DateTime> star_Date, Nullable<System.DateTime> end_Date, Nullable<int> day, Nullable<int> interval, Nullable<int> even_recu_id)
        {
            var star_DateParameter = star_Date.HasValue ?
                new ObjectParameter("Star_Date", star_Date) :
                new ObjectParameter("Star_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var dayParameter = day.HasValue ?
                new ObjectParameter("Day", day) :
                new ObjectParameter("Day", typeof(int));
    
            var intervalParameter = interval.HasValue ?
                new ObjectParameter("Interval", interval) :
                new ObjectParameter("Interval", typeof(int));
    
            var even_recu_idParameter = even_recu_id.HasValue ?
                new ObjectParameter("even_recu_id", even_recu_id) :
                new ObjectParameter("even_recu_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_MonthlyDayRecurrence_Result>("[MTSTXEntities].[fn_MonthlyDayRecurrence](@Star_Date, @End_Date, @Day, @Interval, @even_recu_id)", star_DateParameter, end_DateParameter, dayParameter, intervalParameter, even_recu_idParameter);
        }
    
        [DbFunction("MTSTXEntities", "fn_MonthlyWeekRecurrence")]
        public virtual IQueryable<fn_MonthlyWeekRecurrence_Result> fn_MonthlyWeekRecurrence(Nullable<System.DateTime> star_Date, Nullable<System.DateTime> end_Date, Nullable<int> interval, string option, string days, Nullable<int> even_recu_id)
        {
            var star_DateParameter = star_Date.HasValue ?
                new ObjectParameter("Star_Date", star_Date) :
                new ObjectParameter("Star_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var intervalParameter = interval.HasValue ?
                new ObjectParameter("Interval", interval) :
                new ObjectParameter("Interval", typeof(int));
    
            var optionParameter = option != null ?
                new ObjectParameter("Option", option) :
                new ObjectParameter("Option", typeof(string));
    
            var daysParameter = days != null ?
                new ObjectParameter("Days", days) :
                new ObjectParameter("Days", typeof(string));
    
            var even_recu_idParameter = even_recu_id.HasValue ?
                new ObjectParameter("even_recu_id", even_recu_id) :
                new ObjectParameter("even_recu_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_MonthlyWeekRecurrence_Result>("[MTSTXEntities].[fn_MonthlyWeekRecurrence](@Star_Date, @End_Date, @Interval, @Option, @Days, @even_recu_id)", star_DateParameter, end_DateParameter, intervalParameter, optionParameter, daysParameter, even_recu_idParameter);
        }
    
        [DbFunction("MTSTXEntities", "fn_sche_recu_check")]
        public virtual IQueryable<fn_sche_recu_check_Result> fn_sche_recu_check(Nullable<System.DateTime> star_Date, Nullable<System.DateTime> end_Date, string starttime, string endtime, Nullable<int> pooja_id, string rec)
        {
            var star_DateParameter = star_Date.HasValue ?
                new ObjectParameter("Star_Date", star_Date) :
                new ObjectParameter("Star_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var starttimeParameter = starttime != null ?
                new ObjectParameter("Starttime", starttime) :
                new ObjectParameter("Starttime", typeof(string));
    
            var endtimeParameter = endtime != null ?
                new ObjectParameter("Endtime", endtime) :
                new ObjectParameter("Endtime", typeof(string));
    
            var pooja_idParameter = pooja_id.HasValue ?
                new ObjectParameter("pooja_id", pooja_id) :
                new ObjectParameter("pooja_id", typeof(int));
    
            var recParameter = rec != null ?
                new ObjectParameter("Rec", rec) :
                new ObjectParameter("Rec", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_sche_recu_check_Result>("[MTSTXEntities].[fn_sche_recu_check](@Star_Date, @End_Date, @Starttime, @Endtime, @pooja_id, @Rec)", star_DateParameter, end_DateParameter, starttimeParameter, endtimeParameter, pooja_idParameter, recParameter);
        }
    
        [DbFunction("MTSTXEntities", "fn_WeeklyRecurrence")]
        public virtual IQueryable<fn_WeeklyRecurrence_Result> fn_WeeklyRecurrence(Nullable<System.DateTime> star_Date, Nullable<System.DateTime> end_Date, Nullable<int> interval, string days, Nullable<int> even_recu_id)
        {
            var star_DateParameter = star_Date.HasValue ?
                new ObjectParameter("Star_Date", star_Date) :
                new ObjectParameter("Star_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var intervalParameter = interval.HasValue ?
                new ObjectParameter("Interval", interval) :
                new ObjectParameter("Interval", typeof(int));
    
            var daysParameter = days != null ?
                new ObjectParameter("Days", days) :
                new ObjectParameter("Days", typeof(string));
    
            var even_recu_idParameter = even_recu_id.HasValue ?
                new ObjectParameter("even_recu_id", even_recu_id) :
                new ObjectParameter("even_recu_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_WeeklyRecurrence_Result>("[MTSTXEntities].[fn_WeeklyRecurrence](@Star_Date, @End_Date, @Interval, @Days, @even_recu_id)", star_DateParameter, end_DateParameter, intervalParameter, daysParameter, even_recu_idParameter);
        }
    
        [DbFunction("MTSTXEntities", "fnStringSplitter")]
        public virtual IQueryable<fnStringSplitter_Result> fnStringSplitter(string iDs, string delimiter)
        {
            var iDsParameter = iDs != null ?
                new ObjectParameter("IDs", iDs) :
                new ObjectParameter("IDs", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnStringSplitter_Result>("[MTSTXEntities].[fnStringSplitter](@IDs, @Delimiter)", iDsParameter, delimiterParameter);
        }
    
        [DbFunction("MTSTXEntities", "proc_sche_recu_check")]
        public virtual IQueryable<proc_sche_recu_check_Result> proc_sche_recu_check(Nullable<System.DateTime> star_Date, Nullable<System.DateTime> end_Date, string starttime, string endtime, Nullable<int> pooja_id, string rec)
        {
            var star_DateParameter = star_Date.HasValue ?
                new ObjectParameter("Star_Date", star_Date) :
                new ObjectParameter("Star_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var starttimeParameter = starttime != null ?
                new ObjectParameter("Starttime", starttime) :
                new ObjectParameter("Starttime", typeof(string));
    
            var endtimeParameter = endtime != null ?
                new ObjectParameter("Endtime", endtime) :
                new ObjectParameter("Endtime", typeof(string));
    
            var pooja_idParameter = pooja_id.HasValue ?
                new ObjectParameter("pooja_id", pooja_id) :
                new ObjectParameter("pooja_id", typeof(int));
    
            var recParameter = rec != null ?
                new ObjectParameter("Rec", rec) :
                new ObjectParameter("Rec", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<proc_sche_recu_check_Result>("[MTSTXEntities].[proc_sche_recu_check](@Star_Date, @End_Date, @Starttime, @Endtime, @pooja_id, @Rec)", star_DateParameter, end_DateParameter, starttimeParameter, endtimeParameter, pooja_idParameter, recParameter);
        }
    
        [DbFunction("MTSTXEntities", "Split")]
        public virtual IQueryable<Split_Result> Split(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("String", @string) :
                new ObjectParameter("String", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Split_Result>("[MTSTXEntities].[Split](@String, @Delimiter)", stringParameter, delimiterParameter);
        }
    
        [DbFunction("MTSTXEntities", "udf_Split")]
        public virtual IQueryable<udf_Split_Result> udf_Split(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("String", @string) :
                new ObjectParameter("String", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_Split_Result>("[MTSTXEntities].[udf_Split](@String, @Delimiter)", stringParameter, delimiterParameter);
        }
    }
}
