//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class QBHoma_Customer
    {
        public int No { get; set; }
        public string RequestID { get; set; }
        public string Type { get; set; }
        public string RequestMessage { get; set; }
        public string ResponseMessage { get; set; }
        public bool Mode { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual QBHoma_RequestType QBHoma_RequestType { get; set; }
        public virtual QBHoma_Status QBHoma_Status { get; set; }
    }
}
