//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class QBHoma_Status
    {
        public QBHoma_Status()
        {
            this.d_comp = new HashSet<d_comp>();
            this.d_user_comp = new HashSet<d_user_comp>();
            this.m_category = new HashSet<m_category>();
            this.m_category_type = new HashSet<m_category_type>();
            this.m_service = new HashSet<m_service>();
            this.m_shop_cart = new HashSet<m_shop_cart>();
            this.m_user = new HashSet<m_user>();
            this.QBHoma_ChartOfAccount = new HashSet<QBHoma_ChartOfAccount>();
            this.QBHoma_Customer = new HashSet<QBHoma_Customer>();
            this.QBHoma_Expense = new HashSet<QBHoma_Expense>();
            this.QBHoma_Income = new HashSet<QBHoma_Income>();
            this.m_dona_serv_fee = new HashSet<m_dona_serv_fee>();
            this.m_shop_cart_tran = new HashSet<m_shop_cart_tran>();
        }
    
        public string StatusCode { get; set; }
        public string StatusDscr { get; set; }
    
        public virtual ICollection<d_comp> d_comp { get; set; }
        public virtual ICollection<d_user_comp> d_user_comp { get; set; }
        public virtual ICollection<m_category> m_category { get; set; }
        public virtual ICollection<m_category_type> m_category_type { get; set; }
        public virtual ICollection<m_service> m_service { get; set; }
        public virtual ICollection<m_shop_cart> m_shop_cart { get; set; }
        public virtual ICollection<m_user> m_user { get; set; }
        public virtual ICollection<QBHoma_ChartOfAccount> QBHoma_ChartOfAccount { get; set; }
        public virtual ICollection<QBHoma_Customer> QBHoma_Customer { get; set; }
        public virtual ICollection<QBHoma_Expense> QBHoma_Expense { get; set; }
        public virtual ICollection<QBHoma_Income> QBHoma_Income { get; set; }
        public virtual ICollection<m_dona_serv_fee> m_dona_serv_fee { get; set; }
        public virtual ICollection<m_shop_cart_tran> m_shop_cart_tran { get; set; }
    }
}
