//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class QBHoma_RequestType
    {
        public QBHoma_RequestType()
        {
            this.QBHoma_ChartOfAccount = new HashSet<QBHoma_ChartOfAccount>();
            this.QBHoma_Customer = new HashSet<QBHoma_Customer>();
            this.QBHoma_Expense = new HashSet<QBHoma_Expense>();
            this.QBHoma_Income = new HashSet<QBHoma_Income>();
        }
    
        public string RequestType { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<QBHoma_ChartOfAccount> QBHoma_ChartOfAccount { get; set; }
        public virtual ICollection<QBHoma_Customer> QBHoma_Customer { get; set; }
        public virtual ICollection<QBHoma_Expense> QBHoma_Expense { get; set; }
        public virtual ICollection<QBHoma_Income> QBHoma_Income { get; set; }
    }
}
