//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_bstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class walk_in_devo_info
    {
        public int walk_in_devo_id { get; set; }
        public string walk_in_devo_fname { get; set; }
        public string walk_in_devo_lname { get; set; }
        public string Walk_In_Devo_Addr { get; set; }
        public Nullable<int> Walk_In_Devo_nat { get; set; }
        public string Walk_In_Devo_Goth { get; set; }
        public string Walk_In_Devo_City { get; set; }
        public Nullable<int> Walk_In_Devo_State { get; set; }
        public string Walk_In_Devo_State_others { get; set; }
        public Nullable<int> Walk_In_Devo_Cntry { get; set; }
        public string Walk_In_Devo_Cntry_Others { get; set; }
        public string Walk_In_Devo_Zip { get; set; }
        public string Walk_In_Devo_Email { get; set; }
        public string Walk_In_Devo_Ph { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
    }
}
